// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBdR7pCZwds7s0by_WqTIOMklrk54oEZI',
    appId: '1:226093502936:web:16d8d861adb4cba4ec22ad',
    messagingSenderId: '226093502936',
    projectId: 'negocio-rural-da5b3',
    authDomain: 'negocio-rural-da5b3.firebaseapp.com',
    storageBucket: 'negocio-rural-da5b3.appspot.com',
    measurementId: 'G-C90D2QVDXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5LE1NkyCNIekW5D45PywGnaJhl-7nVHE',
    appId: '1:226093502936:android:8890ea1bbec20265ec22ad',
    messagingSenderId: '226093502936',
    projectId: 'negocio-rural-da5b3',
    storageBucket: 'negocio-rural-da5b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4ryeQeEC5PuAEEN_Is0aoiNtAfpy32iI',
    appId: '1:226093502936:ios:850448150cc93033ec22ad',
    messagingSenderId: '226093502936',
    projectId: 'negocio-rural-da5b3',
    storageBucket: 'negocio-rural-da5b3.appspot.com',
    iosClientId: '226093502936-bpf3ge91co0qc1aos5arbklvbe6ektnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.gadoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4ryeQeEC5PuAEEN_Is0aoiNtAfpy32iI',
    appId: '1:226093502936:ios:116ac93f938a511cec22ad',
    messagingSenderId: '226093502936',
    projectId: 'negocio-rural-da5b3',
    storageBucket: 'negocio-rural-da5b3.appspot.com',
    iosClientId: '226093502936-a7eqe0o9ddutr6g0rrauv1rti9takvve.apps.googleusercontent.com',
    iosBundleId: 'com.example.gadoApp.RunnerTests',
  );
}
