### Listar usuários
GET localhost:8080/api/users

### Cadastra um usuário
POST localhost:8080/api/users
Content-Type: application/json

{
  "name": "Vinicius Godoy",
  "email": "vinigodoy@gmail.com",
  "password": "password"
}

### Lista o usuário 2
GET localhost:8080/api/users

### Lista o próprio usuário
GET localhost:8080/api/users/me
Authorization: Bearer {{token}}

### Login
POST localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "vinigodoy@gmail.cosm",
  "password": "password"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.user.id)
%}

### Login com admin
POST localhost:8080/api/users/login
Content-Type: application/json

{
  "cellphone": "4288148286",
  "password": "admin"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.user.id)
%}

### Exclui o usuário
DELETE localhost:8080/api/users/2
Authorization: Bearer {{token}}

### Adiciona um novo anúncio de animal ao usuário com o id 2
POST localhost:8080/api/users/2/ads/animal
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Vaca malhada",
  "price": 2000.0,
  "localization": "Curitiba/PR",
  "images": ["rato.png"]
}

### Adiciona um novo anúncio de terra ao usuário com o id 2
POST localhost:8080/api/users/2/ads/land
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Campo Bonito",
  "price": 500000.0,
  "localization": "Curitiba/PR"
}

### Adiciona um novo anúncio de maquinario ao usuário com o id 2
POST localhost:8080/api/users/2/ads/machinery
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Colheitadeira",
  "price": 2000.0,
  "localization": "Curitiba/PR"
}

### Retorna todos os anuncios de animais
GET localhost:8080/api/users/ads/animal
Content-Type: application/json
Authorization: Bearer {{token}}

### Retorna todos os anuncios de terras
GET localhost:8080/api/users/ads/land

### Retorna todos os anuncios de terras
GET localhost:8080/api/users/ads/land/2



### Retorna todos os anuncios de máquinas
GET localhost:8080/api/users/ads/machinery

### Retorna todos os anuncios criados pelo usuario 2
GET localhost:8080/api/users/2/ads

### Retorna todos os anuncios favoritados pelo usuario 2
GET localhost:8080/api/users/2/favorites

### Retorna todas as publicidades
GET localhost:8080/api/users/adm/ads
Content-Type: application/json
Authorization: Bearer {{token}}
